---
dataloader:
  train:
    dataset:
      type: DavisWithMaskDataset
      root_path: /mnt/data2T/junyuan/Datasets/EventUNetDataset
      split: train
      default_resolution: [256, 256]
      events_interpolation: causal_linear
      mode: event
    prefetch_factor: 2
    batch_size: 32
    shuffle: true
    drop_last: false
    num_workers: 8
    persistent_workers: true
    pin_memory: true

  val:
    dataset:
      type: DavisWithMaskDataset
      root_path: /mnt/data2T/junyuan/Datasets/EventUNetDataset
      split: val
      default_resolution: [256, 256]
      events_interpolation: causal_linear
      mode: event
    batch_size: 32
    shuffle: false
    drop_last: False
    num_workers: 8
    persistent_workers: true
    pin_memory: true

model:
  type: UNet
  n_channels: 1
  n_classes: 2

train:
  max_epochs: 70
  check_val_every_n_epoch: 1
  ckpt_path: /mnt/data2T/junyuan/eye-tracking/logs/DavisEyeCenter_TennSt/version_99/checkpoints/last.ckpt
  optimizer:
    learning_rate: 1.0e-3
    weight_decay: 1.0e-5

val:
  ckpt_path: /mnt/data2T/junyuan/eye-tracking/logs/EPNet_FixedTime10000/version_0/checkpoints/epochepoch=52-val_lossval_loss=13.3284.ckpt

logger:
  type: tensorboard
  save_dir: /mnt/data2T/junyuan/eye-tracking/logs
  name: EventUNet

callback:
  - type: ModelCheckpoint
    monitor: val_mean_distance
    auto_insert_metric_name: true
    save_top_k: 3
    mode: min
    every_n_epochs: 1
    save_last: true
    verbose: true
    filename: "{epoch:02d}-{val_mean_distance:.4f}"
  # - type: S3Checkpoint
  #   monitor: val_p10_acc
  #   auto_insert_metric_name: true
  #   save_top_k: 3
  #   mode: max
  #   every_n_epochs: 1
  #   save_last: true
  #   verbose: true
  #   s3_bucket: s3://junyuan1213
  #   s3_prefix: eveye

  - type: TQDMProgressBar
    refresh_rate: 1

  - type: Timer

  - type: LearningRateMonitor
    logging_interval: epoch
