---
dataloader:
  train:
    dataset:
      type: MemmapDavisEyeCenterDataset
      root_path: /mnt/data2T/junyuan/Datasets/datasets/MemmapDavisEyeCenterDataset
      # root_path: /mnt/data2T/junyuan/eye-tracking/testDataset
      split: train
      time_window: 40000
      frames_per_segment: 50
      sensor_size: [346, 260, 2]
      events_interpolation: causal_linear
      fixed_count: 5000
      spatial_downsaple: true
      saptial_transform: true
      temporal_transform: false
    prefetch_factor: 2
    batch_size: 32
    shuffle: true
    drop_last: false
    num_workers: 8
    persistent_workers: true
    pin_memory: true

  val:
    dataset:
      type: MemmapDavisEyeCenterDataset
      root_path: /mnt/data2T/junyuan/Datasets/datasets/MemmapDavisEyeCenterDataset
      # root_path: /mnt/data2T/junyuan/eye-tracking/testDataset
      split: val
      time_window: 40000
      frames_per_segment: 50
      sensor_size: [346, 260, 2]
      events_interpolation: causal_linear
      fixed_count: 5000
      spatial_downsaple: true
      saptial_transform: false
      temporal_transform: false
    batch_size: 32
    shuffle: false
    drop_last: False
    num_workers: 8
    persistent_workers: true
    pin_memory: true

model:
  type: TennSt
  channels: [2, 8, 16, 32, 48, 64, 80, 96, 112, 128, 256]
  t_kernel_size: 5
  n_depthwise_layers: 4
  detector_head: true
  detector_depthwise: true
  full_conv3d: False
  norms: mixed
  activity_regularization: 0

train:
  max_epochs: 50
  # max_epochs: 1
  check_val_every_n_epoch: 1
  ckpt_path: /mnt/data2T/junyuan/eye-tracking/logs/DavisEyeCenter_TennSt/version_99/checkpoints/last.ckpt
  optimizer:
    learning_rate: 1.0e-3
    weight_decay: 1.0e-5

val:
  ckpt_path: /mnt/data2T/junyuan/eye-tracking/weights/96.89%-FixedCount5000-Down-Aug-NoFlip/checkpoints/epochepoch=47-val_p10_accval_p10_acc=0.9689.ckpt

logger:
  type: tensorboard
  save_dir: /mnt/data2T/junyuan/eye-tracking/logs
  name: FixedCount15000-Down-Aug-NoFlip

callback:
  - type: ModelCheckpoint
    monitor: val_p10_acc
    auto_insert_metric_name: true
    save_top_k: 3
    mode: max
    every_n_epochs: 1
    save_last: true
    verbose: true
    filename: "epoch{epoch:02d}-val_p10_acc{val_p10_acc:.4f}"
  # - type: S3Checkpoint
  #   monitor: val_p10_acc
  #   auto_insert_metric_name: true
  #   save_top_k: 3
  #   mode: max
  #   every_n_epochs: 1
  #   save_last: true
  #   verbose: true
  #   s3_bucket: s3://junyuan1213
  #   s3_prefix: eveye

  - type: TQDMProgressBar
    refresh_rate: 1

  - type: Timer

  - type: LearningRateMonitor
    logging_interval: epoch
