---
dataloader:
  test:
    dataset:
      type: TestDataset
      dataset_path: /mnt/data2T/junyuan/eye-tracking/EV_Eye_dataset/raw_data/Data_davis/user1/left/session_1_0_1/frames
      transform: true
      height: 260
      width: 346
    prefetch_factor: 2
    batch_size: 1
    shuffle: false
    num_workers: 8
    pin_memory: true
    drop_last: true

model:
  type: UNet
  n_channels: 1
  n_classes: 2
  bilinear: true
  # type: DeepLabV3
  # n_classes: 2
  # pretrained: false

test:
  ckpt_path: /mnt/data2T/junyuan/eye-tracking/weights/DavisWithMaskDataset/U-Net/checkpoints/epoch=98-step=25146.ckpt
  map_location: cuda:0
